# Change these first
owner: KitsuneTV # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: Osaka (Website)
    url: https://kitsune.tv/
  - name: Osaka Beta (Beta Website)
    url: https://beta.kitsune.tv/
  - name: Kyoto (API)
    url: https://kyoto.kitsune.tv/
  - name: Neyagawa (Search)
    url: https://neyagawa.kitsune.tv/
  - name: Kyushu (Analytics)
    url: https://kyushu.kitsune.tv/
  - name: Sakai (Poster Proxy)
    url: https://sakai.kitsune.tv/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: dark
  cname: status.kitsune.tv
  # baseUrl: /your-repo-name
  logoUrl: https://kitsune.tv/favicon.svg
  favicon: https://kitsune.tv/favicon.png
  faviconSvg: https://kitsune.tv/favicon.svg
  name: Kitsune Status
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Kitsune is constantly being maintained by its developers around the clock. Status updates and maintenance will be posted here as and when we need to.
  navbar:
    - title: Back to the anime!
      href: https://kitsune.tv/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
